[package]
name = "psnailder_fit"
version = "0.0.0"
edition = "2024"

[dependencies]
basin= { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
rayon = { workspace = true }
psnailder_core = { workspace = true }
psnailder_math = { workspace = true }
psnailder_mock = { workspace = true }
psnailder_tiktak = { workspace = true }

[lints]
workspace = true
