[package]
name = "py-psnailder"
version = "0.1.0"
edition = "2024"

[lib]
name = "_internal"
crate-type = ["cdylib"]

[dependencies]
argmin = { workspace = true }
itertools = { workspace = true }
pyo3 = { workspace = true }
psnailder_core = { workspace = true }
psnailder_fit = { workspace = true }
psnailder_tiktak = { workspace = true }
numpy = { workspace = true }
statrs = { workspace = true }


[features]
default = []
