"""Utilities to generate backgrounds."""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
from scipy import stats

if TYPE_CHECKING:
    from optype import numpy as onp


def generate_initial_background(
    z: onp.Array1D[np.float64],
    vz: onp.Array1D[np.float64],
    z_mesh: onp.Array2D[np.float64],
    vz_mesh: onp.Array2D[np.float64],
) -> onp.Array2D[np.float64]:
    """Generate a symmetric KDE background as the initial background estimate.

    Parameters
    ----------
    z : Array1D[f64]
        The z coordinate of the stars.
    vz : Array1D[f64]
        The Vz velocity of the stars.
    z_mesh : Array2D[f64]
        The z values for each cell.
    vz_mesh : Array2D[f64]
        The Vz values for each cell.

    Returns
    -------
    background : Array2D[f64]
        The symmetric initial background generated by a Gaussian KDE.

    """
    z_mirrored = np.concatenate([z, z])
    vz_mirrored = np.concatenate([vz, -vz])
    kde = stats.gaussian_kde(np.vstack([z_mirrored, vz_mirrored]), bw_method="scott")
    grid_points = np.vstack([z_mesh.ravel(), vz_mesh.ravel()])
    return kde(grid_points).reshape(z_mesh.shape)
