from collections.abc import Sequence

import numpy as np
from optype import numpy as onp

def ln_likelihood_f64(
    data: onp.Array1D[np.float64], prediction: onp.Array1D[np.float64], mask: onp.Array1D[np.float64]
) -> float: ...

class PSpiralComponent:
    def __init__(
        self,
        alpha: float,
        b: float,
        c: float,
        theta0: float,
        scale_factor: float,
        rho: float,
        winding: int,
        flattening_strength: float | None,
    ) -> None: ...
    @property
    def alpha(self) -> float: ...
    @property
    def b(self) -> float: ...
    @property
    def c(self) -> float: ...
    @property
    def theta0(self) -> float: ...
    @property
    def scale_factor(self) -> float: ...
    @property
    def rho(self) -> float: ...
    @property
    def winding(self) -> float: ...
    def perturbation(self, z: onp.Array1D[np.float64], vz: onp.Array1D[np.float64]) -> onp.Array1D[np.float64]: ...

class PSpiralModel:
    def __init__(self, components: Sequence[PSpiralComponent]) -> None: ...
    @property
    def components(self) -> Sequence[PSpiralComponent]: ...
    def perturbation(self, z: onp.Array1D[np.float64], vz: onp.Array1D[np.float64]) -> onp.Array1D[np.float64]: ...

class PSpiralFitter:
    def __init__(self, num_samples: int = 4096, max_iterations: int | None = 50, smoothing_sigma: float = 2.0) -> None: ...
    def fit_spiral_with_background(
        self,
        initial_density: onp.Array1D[np.float64],
        initial_background: onp.Array1D[np.float64],
        mask: onp.Array1D[np.float64],
        mesh_x: onp.Array1D[np.float64],
        mesh_y: onp.Array1D[np.float64],
        shape: tuple[int, int],
    ) -> PSpiralFitResult: ...

class PSpiralFitResult:
    @property
    def initial_model(self) -> PSpiralModel: ...
    @property
    def final_model(self) -> PSpiralModel: ...
    @property
    def data(self) -> onp.Array1D[np.float64]: ...
    @property
    def initial_background(self) -> onp.Array1D[np.float64]: ...
    @property
    def final_background(self) -> onp.Array1D[np.float64]: ...
    @property
    def num_iterations(self) -> int: ...
    @property
    def max_iterations(self) -> int | None: ...
    @property
    def converged(self) -> bool: ...
    @property
    def lnl(self) -> float: ...
    @property
    def initial_pvalue(self) -> float: ...
    @property
    def final_pvalue(self) -> float: ...
